services:
  api:
    build:
      context: . #. means this docker-compose is inside the node api home directory, in this scenario, you can even abandon this option.
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env # Use the same .env file for both services
    working_dir: /usr/src/app
    volumes:
      - ./:/app
    command: npm run dev